export const WORDS = [
    "ANGULAR",
    "BOOTSTRAP",
    "HTML",
    "JAVASCRIPT",
    "VUE",
    "SVELTE",
    "REACT",
    "CSS",
    "BACKBONE",
    "EMBER",
    "JAVA",
    "C++",
    "PYTHON",
    "FLUTTER",
    "SWIFT",
    "KOTLIN",
    "ASSEMBLY",
];
export const TIMEOUTGAME = 20; // seconds